routes/web.php
<?php

use App\Events\PublicMessage;
use App\Http\Controllers\ActualizacionController;
use App\Http\Controllers\PermisoController;
use App\Http\Controllers\RolController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SistemaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::match(['get', 'post'],'/form', [App\Http\Controllers\HomeController::class, 'form'])->name('form');
Route::get('/listado', [App\Http\Controllers\HomeController::class, 'indexEjemplo'])->name('indexEjemplo');
Route::get('/show', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::resource('/sistemas', SistemaController::class)->middleware('auth');
Route::resource('/roles', RolController::class)->parameters(['roles' => 'rol'])->middleware('auth');
Route::resource('/actualizaciones', ActualizacionController::class)->parameters(['actualizaciones' => 'actualizacion'])->middleware('auth');
Route::resource('/permisos', PermisoController::class)->middleware('auth');
Route::resource('/users', UserController::class)->middleware('auth');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'cargo',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    
    public function chats()
    {
        return $this->belongsToMany(Chat::class);
    }

    public function messages()
    {
        return $this->morphMany(Message::class, 'owner');
    }

    public function permisos()
    {
        return $this->belongsToMany(Permiso::class, 'permiso_user');
    }

    public function hasPermiso($permiso)
    {
        if ($this->permisos()->where('nombre', $permiso)->first()) {
            return true;
        }
        return false;
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\Permiso;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index-user', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $Permisos = Permiso::all()->pluck('nombre', 'id');
        return view('users.form-user', compact('Permisos'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        if($request->tipo == 'Importado'){
            $password = md5(uniqid(rand(), true));
            $request->merge([
                'cargo' => '',
                'permiso' => '3',
                'password' =>  $password,
                'password_confirmation' =>  $password,
            ]);
        }

        $this->validate($request, [
            'name' => 'required|string|max:255',
            'cargo' => 'string|max:255|nullable',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:8|confirmed',
        ]);

        $user = User::create([
            'name' => $request->name,
            'cargo' => $request->cargo,
            'email' => $request->email,
            'password' => Hash::make($request->password),
        ]);
        $user->cargo = $request->cargo;
        $user->save(); 

        $user->permisos()->attach($request->permisos);

        return redirect()->route('users.show', $user->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.show-user', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        $Permisos = Permiso::all()->pluck('nombre', 'id');
        return view('users.form-user', compact('user','Permisos'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {

        $this->validate($request, [
            'name' => 'required|string|max:255',
            'cargo' => 'nullable|string|max:255',
            'email' => 'required|string|email|max:255|unique:users,email,'. $user->id ,
            'password' => 'nullable|string|min:8|confirmed',
        ]);

        $user->name = $request->name;
        $user->cargo = $request->cargo;
        $user->email = $request->email;

        if($request->password)
            $user->password = Hash::make($request->password);

        $user->update();

        $user->permisos()->sync($request->permisos);

        return redirect()->route('users.show', $user->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        return redirect()->route('users.index');
    }

}

resources/views/users/form-user.blade.php
@extends('layouts.app')

@section('content')

<div class="form-group">
    <div class="ibox-title">
        @if(isset($user))
            <h5>Actualizar Usuario</h5>
        @else
            <h5>Nuevo Usuario</h5>
        @endisset
    </div>
    <div class="ibox-content">
        @if(isset($user))
            {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
        @else
            {!! Form::open(['route' => 'users.store'], ['class' => 'form-horizontal']) !!}
        @endif
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('name', 'Nombre', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-user"></i>
                        </span>
                    </div>
                    {!! Form::text('name', null, ['class' => 'form-control', 'id' => 'name', 'placeholder' => 'Nombre']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('cargo', 'Cargo', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-stamp"></i>
                        </span>
                    </div>
                    {!! Form::text('cargo', null, ['class' => 'form-control', 'id' => 'cargo', 'placeholder' => 'Cargo']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('permisos', 'Permisos', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-id-badge"></i>
                        </span>
                    </div>
                    {!! Form::select('permisos[]', $Permisos, null, ['class' => 'form-control', 'id'=> 'permisos', 'required', 'multiple']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('email', 'Correo', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-email"></i>
                        </span>
                    </div>
                    {!! Form::text('email', null, ['class' => 'form-control', 'id' => 'email', 'placeholder' => 'Correo']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('password', 'Contraseña', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-lock"></i>
                        </span>
                    </div>
                    {!! Form::password('password', ['class' => 'form-control', 'id' => 'password']) !!}
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    {!! Form::label('password', 'Confirmar Contraseña', ['class' => 'col-lg-2 col-form-label']) !!}
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-lock"></i>
                        </span>
                    </div>
                    {!! Form::password('password_confirmation', ['class' => 'form-control', 'id' => 'password_confirmation']) !!}
                </div>
            </div>
            {!! Form::button('Aceptar', ['class' => 'btn btn-info waves-effect waves-light m-r-10', 'type' => 'submit']) !!}
            {!! Form::button('Cancelar', ['class' => 'btn btn-inverse waves-effect waves-light', 'type' => 'submit']) !!}
        {!! Form::close() !!}
    </div>

</div>
@endsection
@push('scripts')
<script>
    $(document).ready(function() {
        $('#permisos').select2({
            placeholder: 'Seleccione Una o Más Permisos',
        });
    });
</script>
@endpush

resources/views/users/index-user.blade.php
@extends('layouts.app')

@section('content')
<div class="row pb-3">
    <div class="col-md-12">
        <a href="{{ route('users.create') }}" class="btn btn-sm btn-info">Nuevo Usuario</a>
    </div>
</div>
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Usuarios</h4>
                    <h6 class="card-subtitle">listado de usuarios</h6>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cargo</th>
                                    <th scope="col">Permiso</th>
                                    <th scope="col">Correo</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                    <tr>
                                        <td class="text-center"><a
                                                href="{{ route('users.show', $user->id) }}">{{ $user->name }}</a>
                                        </td>
                                        <td>{{ $user->cargo }}</td>
                                        <td>
                                            @foreach ($user->permisos()->get() as $permiso)
                                                <li>
                                                    {{ $permiso->nombre }}
                                                </li>
                                            @endforeach
                                        </td>
                                        <td>{{ $user->email }}</td>
                                    </tr>
                                @endforeach
                            </tbody>    
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush

resources/views/users/show-user.blade.php
@extends('layouts.app')

@section('content')
<div class="row pb-3">
    <div class="col-md-12">
        <a href="{{ route('users.index') }}" class="btn btn-sm btn-info">Listado de Usuarios</a>
    </div>
</div>
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Usuario</h4>
                    <h6 class="card-subtitle">detalle de usuario</h6>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre</th>
                                    <th scope="col">Cargo</th>
                                    <th scope="col">Permiso</th>
                                    <th scope="col">Correo</th>
                                    <th scope="col">Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                    <tr>
                                        <td class="text-center">
                                            {{ $user->name }}
                                        </td>
                                        <td>{{ $user->cargo }}</td>
                                        <td>
                                            @foreach ($user->permisos()->get() as $permiso)
                                                <li>
                                                    {{ $permiso->nombre }}
                                                </li>
                                            @endforeach
                                        </td>
                                        <td>{{ $user->email }}</td>
                                        <td>
                                            <div style="white-space: nowrap">
                                                {{-- <a href="{{ route('roles.edit', $rol->id) }}" data-toggle="tooltip" data-original-title="Edit"> <i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a> --}}
                                                <div style="margin-left: 60px">
                                                    {!! Form::open(['route' => ['users.destroy', $user->id], 'method' => 'delete']) !!}
                                                    <a href="{{ route('users.edit', $user->id) }}" data-toggle="tooltip" data-original-title="Editar"> <i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>
                                                    <button type="submit" class="btn" title="Eliminar">
                                                    <i class="fas fa-window-close text-danger"></i>
                                                    </button>
                                                    {!! Form::close() !!}
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                            </tbody>    
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush