routes/web.php
<?php

use App\Events\PublicMessage;
use App\Http\Controllers\ActualizacionController;
use App\Http\Controllers\PermisoController;
use App\Http\Controllers\RolController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SistemaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::match(['get', 'post'],'/form', [App\Http\Controllers\HomeController::class, 'form'])->name('form');
Route::get('/listado', [App\Http\Controllers\HomeController::class, 'indexEjemplo'])->name('indexEjemplo');
Route::get('/show', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::resource('/sistemas', SistemaController::class)->middleware('auth');
Route::resource('/roles', RolController::class)->parameters(['roles' => 'rol'])->middleware('auth');
Route::resource('/actualizaciones', ActualizacionController::class)->parameters(['actualizaciones' => 'actualizacion'])->middleware('auth');
Route::resource('/permisos', PermisoController::class)->middleware('auth');
Route::resource('/users', UserController::class)->middleware('auth');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

resources/views/actualizaciones/form-actualizacion.blade.php
@extends('layouts.app')

@section('content')

<div class="form-group">
    <div class="ibox-title">
        @if(isset($actualizacion))
            <h5>Actualizar Actualizacion</h5>
        @else
            <h5>Nueva Actualizacion</h5>
        @endisset
    </div>
    <div class="ibox-content">
            @if(isset($actualizacion))
                        {!! Form::model($actualizacion, ['route' => ['actualizaciones.update', $actualizacion->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
                    @else
                        {!! Form::open(['route' => 'actualizaciones.store'], array('class' => 'form-horizontal')) !!}
                    @endif
            <div class="form-group">
                <label for="titulo">Titulo</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-text"></i>
                        </span>
                    </div>
                    {!! Form::text('titulo', null, ['class' => 'form-control', 'id' => 'titulo']) !!}
                </div>
            </div>
            <div class="form-group">
                <label for="descripcion">Descripcion</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="mdi mdi-note-text"></i>
                        </span>
                    </div>
                    {!! Form::textArea('descripcion', null, ['class' => 'form-control', 'id' => 'descripcion', 'rows' => '3']) !!}
                </div>
            </div>
            
            <div class="form-group">
                <label for="rol">Seleccionar rol</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-user"></i>
                        </span>
                    </div>
                    {!! Form::select('roles[]', $roles ?? $Roles,  null, ['class' => 'form-control', 'id'=> 'rol']) !!}
                </div>
            </div>

            <div class="form-group">
                <label for="sistema">Seleccionar sistema</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-desktop"></i>
                        </span>
                    </div>
                    {!! Form::select('sistemas[]', $sistemas ?? $Sistemas,  null, ['class' => 'form-control', 'id'=> 'sistema']) !!}
                </div>
            </div>

            

            {!! Form::button('Aceptar', ['class' => 'btn btn-info waves-effect waves-light m-r-10', 'type' => 'submit']) !!}
            {!! Form::button('Cancelar', ['class' => 'btn btn-inverse waves-effect waves-light', 'type' => 'submit']) !!}
        {!! Form::close() !!}
    </div>

</div>
@endsection

resources/views/actualizaciones/index-actualizacion.blade.php
@extends('layouts.app')

@section('content')
<div class="row pb-3">
    <div class="col-md-12">
        <a href="{{ route('actualizaciones.create') }}" class="btn btn-sm btn-info">Nueva Actualizacion</a>
    </div>
</div>

    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Actualizaciones</h4>
                    <h6 class="card-subtitle">Listado Actualizaciones</h6>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Titulo</th>
                                    <th scope="col">Descripcion</th>
                                    <th scope="col">Rol</th>
                                    <th scope="col">Sistemas</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($actualizaciones as $actualizacion)
                                    <tr>
                                        <td class="text-center"><a href="{{ route('actualizaciones.show', $actualizacion->id) }}">{{ $actualizacion->titulo }}</a></td>
                                        <td>{{ $actualizacion->descripcion }}</td>
                                        <td>
                                            <ul>
                                                @foreach ($actualizacion->roles()->get() as $rol)
                                                    <li>
                                                        @if($rol->trashed())
                                                            {{ $rol->NombreRolNombreSistema}} - Eliminado
                                                        @else
                                                            {{ $rol->NombreRolNombreSistema}}
                                                        @endif
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </td>
                                        <td>
                                            <ul>
                                                @foreach ($actualizacion->sistemas()->get() as $sistema)
                                                    <li>
                                                        @if($sistema->trashed())
                                                            {{ $sistema->nombre}} - Eliminado
                                                        @else
                                                            {{ $sistema->nombre}}
                                                        @endif
                                                    </li>
                                                @endforeach
                                            </ul>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush

resources/views/actualizaciones/show-actualizacion.blade.php
@extends('layouts.app')

@section('content')
<a href="{{ route('actualizaciones.index') }}" class="btn btn-sm btn-info">Listado de actualizaciones</a>
            <div class="row">
                <div class="col-md-8 offset-sm-2">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Actualizaciones</h4>
                            <h6 class="card-subtitle">Descripcion de actualizacion</h6>
                            <div class="table-responsive m-t-40">
                                <table id="myTable" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th scope="col">Titulo</th>
                                            <th scope="col">Descripcion</th>
                                            <th scope="col">Rol</th>
                                            <th scope="col">Sistemas</th>
                                            <th scope="col">Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                            <tr>
                                                <td class="text-center"><a href="{{ route('actualizaciones.show', $actualizacion->id) }}">{{ $actualizacion->titulo }}</a></td>
                                                <td>{{ $actualizacion->descripcion }}</td>
                                                <td>
                                                    <ul>
                                                        @foreach ($actualizacion->roles()->get() as $rol)
                                                            <li>
                                                                @if($rol->trashed())
                                                                    {{ $rol->NombreRolNombreSistema}} - Eliminado
                                                                @else
                                                                    {{ $rol->NombreRolNombreSistema}}
                                                                @endif
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </td>
                                                <td>
                                                    <ul>
                                                        @foreach ($actualizacion->sistemas()->get() as $sistema)
                                                            <li>
                                                                @if($sistema->trashed())
                                                                    {{ $sistema->nombre}} - Eliminado
                                                                @else
                                                                    {{ $sistema->nombre}}
                                                                @endif
                                                            </li>
                                                        @endforeach
                                                    </ul>
                                                </td>
                                                <td>
                                                        {!! Form::open(['route' => ['actualizaciones.destroy', $actualizacion->id], 'method' => 'delete']) !!}
                                                        <a href="{{ route('actualizaciones.edit', $actualizacion->id) }}" data-toggle="tooltip" data-original-title="Editar"> <i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>
                                                        <button type="submit" class="btn" title="Eliminar">
                                                        <i class="fas fa-window-close text-danger"></i>
                                                        </button>
                                                        {!! Form::close() !!}
                                                </td>
                                            </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@stop

@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush