routes/web.php
<?php

use App\Events\PublicMessage;
use App\Http\Controllers\ActualizacionController;
use App\Http\Controllers\PermisoController;
use App\Http\Controllers\RolController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SistemaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Auth;



/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::match(['get', 'post'],'/form', [App\Http\Controllers\HomeController::class, 'form'])->name('form');
Route::get('/listado', [App\Http\Controllers\HomeController::class, 'indexEjemplo'])->name('indexEjemplo');
Route::get('/show', [App\Http\Controllers\HomeController::class, 'show'])->name('show');

Route::resource('/sistemas', SistemaController::class)->middleware('auth');
Route::resource('/roles', RolController::class)->parameters(['roles' => 'rol'])->middleware('auth');
Route::resource('/actualizaciones', ActualizacionController::class)->parameters(['actualizaciones' => 'actualizacion'])->middleware('auth');
Route::resource('/permisos', PermisoController::class)->middleware('auth');
Route::resource('/users', UserController::class)->middleware('auth');

Route::middleware([
    'auth:sanctum',
    config('jetstream.auth_session'),
    'verified'
])->group(function () {
    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

resources/views/roles/form-rol.blade.php
@extends('layouts.app')

@section('content')

<div class="form-group">
    <div class="ibox-title">
        @if(isset($sistema))
            <h5>Actualizar Rol</h5>
        @else
            <h5>Nuevo Rol</h5>
        @endisset
    </div>
    <div class="ibox-content">
            @if(isset($rol))
                        {!! Form::model($rol, ['route' => ['roles.update', $rol->id], 'method' => 'patch', 'class' => 'form-horizontal']) !!}
                    @else
                        {!! Form::open(['route' => 'roles.store'], array('class' => 'form-horizontal')) !!}
                    @endif
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-user"></i>
                        </span>
                    </div>
                    {!! Form::text('nombre', null, ['class' => 'form-control', 'id' => 'nombre', 'placeholder' => 'Nombre']) !!}
                </div>
            </div>

            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">
                            <i class="ti-desktop"></i>
                        </span>
                    </div>
                    {!! Form::select('sistema', $sistemas, isset($rol) ? $rol->sistema()->get()[0]->id : null, ['class' => 'form-control', 'id'=> 'sistema']) !!}
                </div>
            </div>

            

            {!! Form::button('Aceptar', ['class' => 'btn btn-info waves-effect waves-light m-r-10', 'type' => 'submit']) !!}
            {!! Form::button('Cancelar', ['class' => 'btn btn-inverse waves-effect waves-light', 'type' => 'submit']) !!}
        {!! Form::close() !!}
    </div>

</div>
@endsection

resources/views/roles/index-rol.blade.php
@extends('layouts.app')

@section('content')
<div class="row pb-3">
    <div class="col-md-12">
        <a href="{{ route('roles.create') }}" class="btn btn-sm btn-info">Nuevo Rol</a>
    </div>
</div>
    <div class="row">
        <div class="col-md-8 offset-sm-2">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Roles</h4>
                    <h6 class="card-subtitle">Listado de roles</h6>
                    <div class="table-responsive m-t-40">
                        <table id="myTable" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th scope="col">Nombre del rol</th>
                                    <th scope="col">Sistema Relacionado</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($roles as $rol)
                                    <tr>
                                        <td class="text-center"><a href="{{ route('roles.show', $rol->id) }}">{{ $rol->nombre }}</a></td>
                                        @foreach($rol->sistema()->withTrashed()->get() as $sistema)
                                            @if($sistema->trashed())
                                                <td>{{ $sistema->nombre }} - Eliminado</td>
                                            @else
                                                <td>{{ $sistema->nombre }}</td>
                                            @endif
                                        @endforeach
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush

resources/views/roles/show-rol.blade.php
@extends('layouts.app')

@section('content')
<a href="{{ route('roles.index') }}" class="btn btn-sm btn-info">Listado de roles</a>
            <div class="row">
                <div class="col-md-8 offset-sm-2">
                    <div class="card">
                        <div class="card-body">
                            <h4 class="card-title">Rol</h4>
                            <h6 class="card-subtitle">Descripcion de rol</h6>
                            <div class="table-responsive m-t-40">
                                <table id="myTable" class="table table-bordered table-striped">
                                    <thead>
                                        <tr>
                                            <th>Nombre del Rol</th>
                                            <th>Sistema Relacionado</th>
                                            <th>Acciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>{{$rol->nombre}}</td>
                                            <td>{{ $rol->sistema()->get()[0]->nombre }}</td>
                                            <td>
                                                <div style="white-space: nowrap">
                                                    {{-- <a href="{{ route('roles.edit', $rol->id) }}" data-toggle="tooltip" data-original-title="Edit"> <i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a> --}}
                                                    <div style="margin-left: 60px">
                                                        {!! Form::open(['route' => ['roles.destroy', $rol->id], 'method' => 'delete']) !!}
                                                        <a href="{{ route('roles.edit', $rol->id) }}" data-toggle="tooltip" data-original-title="Editar"> <i class="fas fa-pencil-alt text-inverse m-r-10"></i> </a>
                                                        <button type="submit" class="btn" title="Eliminar">
                                                        <i class="fas fa-window-close text-danger"></i>
                                                        </button>
                                                        {!! Form::close() !!}
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

@stop

@push('scripts')
    <script>
        $(function () {
            $('#myTable').DataTable();
        });
    </script>
@endpush